config/routes.rb
Rails.application.routes.draw do
  resources :reservation_histroys
  resources :adminpages
  get 'pages/show'

  get 'pages/index'

  resources :searches
  resources :booking_histroys
  resources :rooms
  resources :users
  
  get 'contact/index'

  get 'contact/show'

  namespace :logg do
    get 'front/index'
  end

  namespace :logg do
    get 'front/show'
  end

  get 'about/show'

  get 'about/index'

  get 'home/show'

  get 'home/index'

  namespace :admin do
    get 'front/index'
  end

  namespace :admin do
    get 'front/show'
  end


  root 'home#show'

  get 'logg' =>'logg/front#show'
  get 'login' =>'sessions#new'
  get 'users' => 'home#show'
  get 'home' =>'home#show'
  get 'contact' =>'contact#show'
  get 'logout' =>'sessions#destroy'
  get 'about' =>'about#index'


  post 'login' => 'sessions#create'
  get 'admin' =>'adminpages#index'

  resources :rooms do
    member do
      get 'book'
      get 'schedule'
    end
  end

  resources :booking_histroys do
    member do
      post 'validBooking'
      get 'releaseBooking'
      get 'deleteBooking'
    end
  end

  resources :reservation_histroys do
    member do
      get 'viewHistroy'
    end
  end
  resources :adminpages do
    member do
      get 'userBookingHistroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  def search_rooms
    rooms = Room.all
    rooms = rooms.where(["roomnumber = ?", roomnumber ]) if roomnumber.present?
    rooms = rooms.where(["building LIKE ?", building ]) if building.present?
    rooms = rooms.where(["status LIKE ?", status]) if status.present?
    rooms = rooms.where(["size LIKE ?", size]) if size.present?
    return rooms
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @roomnumber = Room.uniq.pluck(:roomnumber)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:roomnumber, :size, :status, :building)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(search) do |f| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roomnumber %>
    <%= f.number_field :roomnumber %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Roomnumber</th>
      <th>Size</th>
      <th>Status</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.roomnumber %></td>
        <td><%= search.size %></td>
        <td><%= search.status %></td>
        <td><%= search.building %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |s| %>

    <div class="field">
      <%= s.label :roomnumber %><br />
      <%= s.text_field :roomnumber %>
    </div>

    <div class="field">
      <%= s.label :size %><br>
      <%= s.select :size, ['4', '6', '8'] %>
    </div>
    <div class="field">
      <%= s.label :status %><br>
      <%= s.select :status, ['available', 'booked'] %>
    </div>
    <div class="field">
      <%= s.label :building %><br>
      <%= s.select :building, ['James B. Hunt', 'D.H. Hill' ] %>
    </div>

    <div class = "action"><%= s.submit "Search", class: "pure-button pure-button-primary" %></div>

<% end %>

<p> <%= link_to 'Back', rooms_path %></p>

app/views/searches/show.html.erb
<h1>Search Result</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_rooms.empty? %>
    <p> No records found</p>

<%else %>

    <% @search.search_rooms.each do |c| %>
        <br>
        <div class = "div">
          <p>Room Number: <%= c.roomnumber %></p>
          <p>Building: <%= c.building %> </p>
          <p>Status: <%= c.status %></p>
          <p>Size: <%= c.size %></p>
        </div>
    <% end %>

<% end %>