config/routes.rb
Rails.application.routes.draw do
  resources :reservation_histroys
  resources :adminpages
  get 'pages/show'

  get 'pages/index'

  resources :searches
  resources :booking_histroys
  resources :rooms
  resources :users
  
  get 'contact/index'

  get 'contact/show'

  namespace :logg do
    get 'front/index'
  end

  namespace :logg do
    get 'front/show'
  end

  get 'about/show'

  get 'about/index'

  get 'home/show'

  get 'home/index'

  namespace :admin do
    get 'front/index'
  end

  namespace :admin do
    get 'front/show'
  end


  root 'home#show'

  get 'logg' =>'logg/front#show'
  get 'login' =>'sessions#new'
  get 'users' => 'home#show'
  get 'home' =>'home#show'
  get 'contact' =>'contact#show'
  get 'logout' =>'sessions#destroy'
  get 'about' =>'about#index'


  post 'login' => 'sessions#create'
  get 'admin' =>'adminpages#index'

  resources :rooms do
    member do
      get 'book'
      get 'schedule'
    end
  end

  resources :booking_histroys do
    member do
      post 'validBooking'
      get 'releaseBooking'
      get 'deleteBooking'
    end
  end

  resources :reservation_histroys do
    member do
      get 'viewHistroy'
    end
  end
  resources :adminpages do
    member do
      get 'userBookingHistroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :booking_histroys, dependent: :destroy
  enum status: {:Available => "available", :Booked => "booked"}
  enum building: { :Hunt => "James B. Hunt", :Hill => "D.H. Hill"}
  enum size: {:small => "4", :medium => "6", :large => "8"}

  validates_uniqueness_of :roomnumber
  validates_numericality_of :roomnumber, :only_integer => true

  def self.search(search)
    if search
      where(["building LIKE ?", "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index

    @rooms = Room.all
    @rooms = Room.search(params[:search])
    if(session[:user_id] == nil)
      flash[:warning] = "Login to book a room"
      redirect_to login_url
    else
      loggedUser = User.find(session[:user_id])
      if(loggedUser.ornot == 1)
        @superuser = true
      else
        @superuser = false
      end
    end
  end

  def schedule
    @room = Room.find(params[:id])
      whereClause = "rooms_id = #{params[:id]}"
      ids = ReservationHistroy.where(whereClause).ids
      bookingHistroyRoom = []
      if(!ids.empty?)
        ids.each do |x|
          bh = ReservationHistroy.find(x)
          if(bh != nil)
            bookingHistroyRoom << bh
          end
        end
      end

      @bookedSlots = bookingHistroyRoom
    puts "End"
    end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  def book
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    whereClause = "rooms_id = #{@room.id}"
    @bhc = BookingHistroysController.new

git     ids = BookingHistroy.where(whereClause).ids
    ids.each do |id|
      bh = BookingHistroy.find(id)
      if(bh != nil)
        @bhc.deleteBooking(bh)
      end
    end

    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:roomnumber, :size, :status, :building, :date, :time)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
    <% if @room.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

          <ul>
            <% @room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :roomnumber %><br>
      <%= f.number_field :roomnumber %>
    </div>
    <div class="field">
      <%= f.label :size %><br>
      <%= f.select :size, ['small', 'medium', 'large'] %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.select :status, ['Available', 'Booked'] %>
    </div>
    <div class="field">
      <%= f.label :building %><br>
      <%= f.select :building, ['James B. Hunt', 'D.H. Hill'] %>
    </div>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.time_select :time %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/rooms/book.html.erb
<h1>Book Room <%=@room.roomnumber %></h1>
<%= form_for(@room, url: validBooking_booking_histroy_path(@room),method: :post) do |f| %>
    <% if @room.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

          <ul>
            <% @room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br>
    Room Number : <%= @room.roomnumber %>
    <br>

    <br>
    Room Size : <%= @room.size %>
    <br>

    <br>
    Building : <%= @room.building %>
    <br>
    <br>

    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.time_select :time %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Back', rooms_path %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class ="well">
  <p id="notice"><%= notice %></p>
<style>
  table, th, td {
    border: 1px solid black;
  }
</style>
<h1>Book A Room
  <% if(@superuser == true)%>
  <%= link_to 'New Room', new_room_path, class:'btn btn-success pull-right' %>
      <%end%>
</h1>

<%= form_tag rooms_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search via Building" %>
<% end %>

<%= link_to "Advanced Search", new_search_path %>
<br><br>

<table class =" table table-stripped">
  <thead>
  <tr>
    <th>Room Number</th>
    <th>Building</th>
    <th>Size</th>
    <th> Schedule</th>
    <th colspan="5">Actions available</th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomnumber %></td>
        <td><%= room.building %></td>
        <td><%= room.size %></td>
        <td><%= link_to 'View Schedule', schedule_room_path(room) %></td>
        <td><%= link_to 'Show', room %></td>
        <% if(@superuser == true)%>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else%>
            <% end%>
        <td><%= link_to 'Book', book_room_path(room) %></td>
        <td><%= link_to 'Release', releaseBooking_booking_histroy_path(room) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


</div>

<%= link_to 'Edit your profile', edit_user_path(session[:user_id]) %>
<%= link_to 'View my Booking History', viewHistroy_reservation_histroy_path(session[:user_id]) %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/schedule.html.erb
<p id="notice"><%= notice %></p>
<style>
  table, th, td {
    border: 1px solid black;
  }
</style>
<h1>Schedule for Room <%= @room.roomnumber%></h1>

<table>
  <thead>
  <tr>
    <th>Room Number</th>
    <th>Booked From</th>
    <th>Booked To</th>
    <th>Booked On</th>
    <th>Booked by</th>
  </tr>
  </thead>

  <tbody>
  <% @bookedSlots.each do |slot| %>
      <tr>
        <td><%= slot.rooms_id %></td>
        <td><%= slot.from.strftime('%H:%M') %></td>
        <td><%= slot.to.strftime('%H:%M') %></td>
        <td><%= slot.date %></td>
        <td>User<%=slot.users_id%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Book Room', book_room_path(@room) %>
<br>
<%= link_to 'Back', rooms_url %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roomnumber:</strong>
  <%= @room.roomnumber %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<p>
  <strong>Date:</strong>
  <%= @room.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @room.time %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>