config/routes.rb
Rails.application.routes.draw do
  resources :reservation_histroys
  resources :adminpages
  get 'pages/show'

  get 'pages/index'

  resources :searches
  resources :booking_histroys
  resources :rooms
  resources :users
  
  get 'contact/index'

  get 'contact/show'

  namespace :logg do
    get 'front/index'
  end

  namespace :logg do
    get 'front/show'
  end

  get 'about/show'

  get 'about/index'

  get 'home/show'

  get 'home/index'

  namespace :admin do
    get 'front/index'
  end

  namespace :admin do
    get 'front/show'
  end


  root 'home#show'

  get 'logg' =>'logg/front#show'
  get 'login' =>'sessions#new'
  get 'users' => 'home#show'
  get 'home' =>'home#show'
  get 'contact' =>'contact#show'
  get 'logout' =>'sessions#destroy'
  get 'about' =>'about#index'


  post 'login' => 'sessions#create'
  get 'admin' =>'adminpages#index'

  resources :rooms do
    member do
      get 'book'
      get 'schedule'
    end
  end

  resources :booking_histroys do
    member do
      post 'validBooking'
      get 'releaseBooking'
      get 'deleteBooking'
    end
  end

  resources :reservation_histroys do
    member do
      get 'viewHistroy'
    end
  end
  resources :adminpages do
    member do
      get 'userBookingHistroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking_histroy.rb
class BookingHistroy < ApplicationRecord
  has_and_belongs_to_many :rooms
end

app/controllers/booking_histroys_controller.rb
class BookingHistroysController < ApplicationController
  before_action :set_booking_histroy, only: [:show, :edit, :update, :destroy]

  # GET /booking_histroys
  # GET /booking_histroys.json
  def index
    @booking_histroys = BookingHistroy.all
  end

  # GET /booking_histroys/1
  # GET /booking_histroys/1.json
  def show
  end

  # GET /booking_histroys/new
  def new
    @booking_histroy = BookingHistroy.new
  end

  def releaseBooking
    @booking_histroys = Array.new
    whereClause = "rooms_id = #{params[:id]}"
    ids = BookingHistroy.where(whereClause).ids
    ids.each do |bh|
      bookingHistroyRoom = BookingHistroy.find(bh)
      @booking_histroys << bookingHistroyRoom
    end
  end

  def validBooking
    Time.zone = 'UTC'
    if Date.valid_date?(params[:room]["date(1i)"].to_s.to_i,params[:room]["date(2i)"].to_s.to_i,params[:room]["date(3i)"].to_s.to_i)
      myDate = Date.new(params[:room]["date(1i)"].to_s.to_i,params[:room]["date(2i)"].to_s.to_i,params[:room]["date(3i)"].to_s.to_i);

      myTime =  Time.new(params[:room]["date(1i)"].to_s.to_i,params[:room]["date(2i)"].to_s.to_i,params[:room]["date(3i)"].to_s.to_i,params[:room]["time(4i)"].to_s.to_i,params[:room]["time(5i)"].to_s.to_i).in_time_zone("UTC");

      @room = Room.find(params[:id])
      if(myDate < Date.today)
        flash[:warning] = "Select either today's date or a later one."
        redirect_to book_room_url
      else
        if (myDate > (Date.today + 7.days))
          flash[:warning] = "You can book only upto one week in advance."
          redirect_to book_room_url
        else
          if(myTime < Time.now)
            flash[:warning] = "You cannot book for the past!. #{myTime}. Time now #{Time.now}"
            redirect_to book_room_url
          else
            booked = false
            idRoom = @room.id.to_i
            whereClause = "rooms_id = #{idRoom}"
            roomsBookingHistroy = BookingHistroy.where(whereClause).ids
            if(!roomsBookingHistroy.empty?)
              roomsBookingHistroy.each do |bh|
                row = BookingHistroy.find(bh)
                myDateToDate = myDate.to_date
                rowdate = row.date
                if(myDateToDate == rowdate)
                  rowfrom = row.from.strftime('%H:%M')
                  rowto = row.to.strftime('%H:%M')
                  starttime = myTime.strftime('%H:%M')
                  endtime = (myTime + 2.hours).strftime('%H:%M')

                  if((starttime >= rowfrom) && (starttime <= rowto))
                    flash[:warning] = "This slot is already booked!"
                    booked = true
                    break
                  else
                    if((endtime >= rowfrom) && (endtime <= rowto))
                      flash[:warning] = "This slot is already booked!"
                      booked = true
                      break
                    end
                  end
                end

              end
            end
            if(!booked)
              toTime = myTime + 2.hours
              hashArg = {:from => myTime, :to => toTime, :date => myDate, :rooms_id => idRoom}
              @booking_histroy = BookingHistroy.new(hashArg)
              @booking_histroy.save

              #Adding it to the reservation histroy
              hashArgReservation = {:from => myTime, :to => toTime, :date => myDate, :rooms_id => idRoom, :users_id => session[:user_id]}
              @reservation_histroy = ReservationHistroy.new(hashArgReservation)
              @reservation_histroy.save

              redirect_to rooms_url
            else
              redirect_to book_room_url
            end

          end

        end

      end
    else
      flash[:warning] = "Select a Valid Date."
      redirect_to book_room_url
    end
  end




  # GET /booking_histroys/1/edit
  def edit
  end

  # POST /booking_histroys
  # POST /booking_histroys.json
  def create
    @booking_histroy = BookingHistroy.new(booking_histroy_params)

    respond_to do |format|
      if @booking_histroy.save
        format.html { redirect_to @booking_histroy, notice: 'Booking histroy was successfully created.' }
        format.json { render :show, status: :created, location: @booking_histroy }
      else
        format.html { render :new }
        format.json { render json: @booking_histroy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_histroys/1
  # PATCH/PUT /booking_histroys/1.json
  def update
    respond_to do |format|
      if @booking_histroy.update(booking_histroy_params)
        format.html { redirect_to @booking_histroy, notice: 'Booking histroy was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking_histroy }
      else
        format.html { render :edit }
        format.json { render json: @booking_histroy.errors, status: :unprocessable_entity }
      end
    end
  end

  def deleteBooking(bookingHistroy)
    @booking_histroy = bookingHistroy
    whereClause = "rooms_id = #{@booking_histroy.rooms_id}"
    ids = ReservationHistroy.where(whereClause).ids
    ids.each do |id|
      rh = ReservationHistroy.find(id)
      if(rh != nil)
            rh.destroy
      end
    end
    @booking_histroy.destroy

  end

  # DELETE /booking_histroys/1
  # DELETE /booking_histroys/1.json
  def destroy
    whereClause = "rooms_id = #{@booking_histroy.rooms_id} AND users_id=#{session[:user_id]}"
    #AND :to=#{@booking_histroy.to} AND :date=#{@booking_histroy.date}"
    ids = ReservationHistroy.where(whereClause).ids
    ids.each do |id|
      rh = ReservationHistroy.find(id)
      if(rh != nil)
        if(rh.from == @booking_histroy.from)
          if(rh.to == @booking_histroy.to)
            if(rh.date == @booking_histroy.date)
              rh.destroy
            end
          end
        end
      end
    end
    @booking_histroy.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Booking histroy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_booking_histroy
    @booking_histroy = BookingHistroy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_histroy_params
    params.require(:booking_histroy).permit(:from, :to, :date)
  end
end

app/helpers/booking_histroys_helper.rb
module BookingHistroysHelper
end

app/views/booking_histroys/_form.html.erb
<%= form_for(@booking_histroy) do |f| %>
    <% if @booking_histroy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking_histroy.errors.count, "error") %> prohibited this booking_histroy from being saved:</h2>

          <ul>
            <% @booking_histroy.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :from %><br>
      <%= f.time_select :from %>
    </div>
    <div class="field">
      <%= f.label :to %><br>
      <%= f.time_select :to %>
    </div>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.time_select :date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/booking_histroys/edit.html.erb
<h1>Editing Booking Histroy</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking_histroy %> |
<%= link_to 'Back', booking_histroys_path %>

app/views/booking_histroys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Booking Histroys</h1>

<table>
  <thead>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @booking_histroys.each do |booking_histroy| %>
      <tr>
        <td><%= booking_histroy.from %></td>
        <td><%= booking_histroy.to %></td>
        <td><%= booking_histroy.date %></td>
        <td><%= link_to 'Show', booking_histroy %></td>
        <td><%= link_to 'Edit', edit_booking_histroy_path(booking_histroy) %></td>
        <td><%= link_to 'Destroy', booking_histroy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking histroy', new_booking_histroy_path %>

app/views/booking_histroys/new.html.erb
<h1>New Booking Histroy</h1>

<%= render 'form' %>

<%= link_to 'Back', booking_histroys_path %>

app/views/booking_histroys/releaseBooking.html.erb
<p id="notice"><%= notice %></p>
<style>
  table, th, td {
    border: 1px solid black;
  }
</style>
<h1>Listing Booking Histroys</h1>

<table>
  <thead>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Date</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @booking_histroys.each do |booking_histroy| %>
      <tr>
        <td><%= booking_histroy.from.strftime('%H:%M') %></td>
        <td><%= booking_histroy.to.strftime('%H:%M') %></td>
        <td><%= booking_histroy.date %></td>
        <td><%= link_to 'Destroy', booking_histroy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'BACK', rooms_url %>

app/views/booking_histroys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @booking_histroy.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @booking_histroy.to %>
</p>

<p>
  <strong>Date:</strong>
  <%= @booking_histroy.date %>
</p>

<%= link_to 'Edit', edit_booking_histroy_path(@booking_histroy) %> |
<%= link_to 'Back', booking_histroys_path %>