config/routes.rb
Rails.application.routes.draw do
  resources :reservation_histroys
  resources :adminpages
  get 'pages/show'

  get 'pages/index'

  resources :searches
  resources :booking_histroys
  resources :rooms
  resources :users
  
  get 'contact/index'

  get 'contact/show'

  namespace :logg do
    get 'front/index'
  end

  namespace :logg do
    get 'front/show'
  end

  get 'about/show'

  get 'about/index'

  get 'home/show'

  get 'home/index'

  namespace :admin do
    get 'front/index'
  end

  namespace :admin do
    get 'front/show'
  end


  root 'home#show'

  get 'logg' =>'logg/front#show'
  get 'login' =>'sessions#new'
  get 'users' => 'home#show'
  get 'home' =>'home#show'
  get 'contact' =>'contact#show'
  get 'logout' =>'sessions#destroy'
  get 'about' =>'about#index'


  post 'login' => 'sessions#create'
  get 'admin' =>'adminpages#index'

  resources :rooms do
    member do
      get 'book'
      get 'schedule'
    end
  end

  resources :booking_histroys do
    member do
      post 'validBooking'
      get 'releaseBooking'
      get 'deleteBooking'
    end
  end

  resources :reservation_histroys do
    member do
      get 'viewHistroy'
    end
  end
  resources :adminpages do
    member do
      get 'userBookingHistroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adminpage.rb
class Adminpage < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_histroy.rb
class BookingHistroy < ApplicationRecord
  has_and_belongs_to_many :rooms
end

app/models/reservation_histroy.rb
class ReservationHistroy < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :booking_histroys, dependent: :destroy
  enum status: {:Available => "available", :Booked => "booked"}
  enum building: { :Hunt => "James B. Hunt", :Hill => "D.H. Hill"}
  enum size: {:small => "4", :medium => "6", :large => "8"}

  validates_uniqueness_of :roomnumber
  validates_numericality_of :roomnumber, :only_integer => true

  def self.search(search)
    if search
      where(["building LIKE ?", "%#{search}%"])
    else
      all
    end
  end

end

app/models/search.rb
class Search < ApplicationRecord
  def search_rooms
    rooms = Room.all
    rooms = rooms.where(["roomnumber = ?", roomnumber ]) if roomnumber.present?
    rooms = rooms.where(["building LIKE ?", building ]) if building.present?
    rooms = rooms.where(["status LIKE ?", status]) if status.present?
    rooms = rooms.where(["size LIKE ?", size]) if size.present?
    return rooms
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  
  validates :email, presence: true, length: { maximum: 255 },

                    format: { with: VALID_EMAIL_REGEX },

                    uniqueness: { case_sensitive: false }

  validates :password_digest, presence: true, length: { minimum: 4 }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end

  def index
  end
  
  layout 'pages/application'
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index

    @rooms = Room.all
    @rooms = Room.search(params[:search])
    if(session[:user_id] == nil)
      flash[:warning] = "Login to book a room"
      redirect_to login_url
    else
      loggedUser = User.find(session[:user_id])
      if(loggedUser.ornot == 1)
        @superuser = true
      else
        @superuser = false
      end
    end
  end

  def schedule
    @room = Room.find(params[:id])
      whereClause = "rooms_id = #{params[:id]}"
      ids = ReservationHistroy.where(whereClause).ids
      bookingHistroyRoom = []
      if(!ids.empty?)
        ids.each do |x|
          bh = ReservationHistroy.find(x)
          if(bh != nil)
            bookingHistroyRoom << bh
          end
        end
      end

      @bookedSlots = bookingHistroyRoom
    puts "End"
    end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  def book
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    whereClause = "rooms_id = #{@room.id}"
    @bhc = BookingHistroysController.new

git     ids = BookingHistroy.where(whereClause).ids
    ids.each do |id|
      bh = BookingHistroy.find(id)
      if(bh != nil)
        @bhc.deleteBooking(bh)
      end
    end

    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:roomnumber, :size, :status, :building, :date, :time)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/login/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Index</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>

</head>

<body>

<div class="container">

  <form class="form-signin">
    <h2 class="form-signin-heading">LibApp Login</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>

</div> <!-- /container -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>
</body>
</html>

app/views/layouts/pages/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Index</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

  </head>

  <body>


  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= home_index_path%>">Library App</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", home_index_path %>></li>
          <li><%= link_to "Bookings", admin_front_show_path %></li>
          <li class="active"><%= link_to "Manage Accounts", admin_front_index_path %>></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          </ul>

      </div><!--/.nav-collapse -->
    </div>
    </div>
  </nav>

  <section>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <%= yield %>
           </div>

      </div>

    </div>
  </section>

  <%= render 'partials/footer' %>
  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="js/bootstrap.js"></script>
  </body>
</html>